#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelpShiftTest.Resource", IsApplication=true)]

namespace HelpShiftTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int hs__actionBarTabTextStyle = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int hs__actionbarCompatItemBaseStyle = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int hs__actionbarCompatProgressIndicatorStyle = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int hs__actionbarCompatTitleStyle = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int hs__selectableItemBackground = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int hs__actionBarBackgroundColor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int hs__actionBarStackedColor = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int hs__actionBarTabIndicatorColor = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hs__actionBarTextColorPrimary = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hs__actionBarTextColorSecondary = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int hs__confirmationAcceptedTextColor = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int hs__confirmationRejectedTextColor = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hs__light_horizontal_stub_bg = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int hs__messages_text_color = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int hs__msg_user_chat_bubble_separator = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int hs__notificationIconColor = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int hs__question_footer_color = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hs__send_reply_icon_color = 2130968588;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int hs__actionbar_compat_button_home_width = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hs__actionbar_compat_button_width = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int hs__actionbar_compat_height = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int hs__actionbar_compat_icon_vertical_padding = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int hs__button_padding_right = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int hs__content_wrapper_padding = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int hs__content_wrapper_top_padding = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int hs__faqs_sync_status_height = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int hs__listPreferredItemHeightSmall = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int hs__listPreferredItemPaddingBottom = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int hs__listPreferredItemPaddingLeft = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int hs__listPreferredItemPaddingRight = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int hs__listPreferredItemPaddingTop = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int hs__marginLeft = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int hs__msgActionButtonPadding = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int hs__msgPreferredItemPaddingBottom = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int hs__msgPreferredItemPaddingLeft = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int hs__msgPreferredItemPaddingRight = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int hs__msgPreferredItemPaddingTop = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int hs__msg_timestamp_alpha = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int hs__msg_timestamp_padding = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int hs__question_text_padding = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int hs__textSizeSmall = 2131034134;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hs__action_attach = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hs__action_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hs__action_cancel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hs__action_new_picture = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hs__action_no = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hs__action_review = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hs__action_search = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int hs__action_yes = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int hs__actionbar_compat_item = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int hs__actionbar_compat_item_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int hs__actionbar_compat_item_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int hs__actionbar_shadow = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int hs__attach_screenshot = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int hs__chat = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int hs__chat_bubble_admin = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int hs__chat_bubble_user = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int hs__chat_new = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int hs__chat_new_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int hs__chat_notif = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int hs__edit_text_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int hs__faq_helpful = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int hs__faq_unhelpful = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int hs__faqs_updated = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int hs__logo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int hs__notification_badge = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int hs__report_issue = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int hs__screenshot_clear = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int hs__send = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int hs__textfield_activated_holo_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int hs__textfield_default_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int hs__textfield_disabled_focused_holo_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int hs__textfield_disabled_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int hs__textfield_focused_holo_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int hs__warning = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Icon = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060040
			public const int Button1 = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int Button2 = 2131099713;
			
			// aapt resource value: 0x7f06000c
			public const int additional_feedback = 2131099660;
			
			// aapt resource value: 0x7f06001e
			public const int admin_message = 2131099678;
			
			// aapt resource value: 0x7f060034
			public const int button_containers = 2131099700;
			
			// aapt resource value: 0x7f06001f
			public const int button_separator = 2131099679;
			
			// aapt resource value: 0x7f060035
			public const int change = 2131099701;
			
			// aapt resource value: 0x7f060010
			public const int csat_dislike_msg = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int csat_like_msg = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int csat_message = 2131099663;
			
			// aapt resource value: 0x7f060019
			public const int csat_view_stub = 2131099673;
			
			// aapt resource value: 0x7f06000d
			public const int divider = 2131099661;
			
			// aapt resource value: 0x7f060033
			public const int horizontal_divider = 2131099699;
			
			// aapt resource value: 0x7f060043
			public const int hs__action_add_conversation = 2131099715;
			
			// aapt resource value: 0x7f060029
			public const int hs__action_faq_helpful = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int hs__action_faq_unhelpful = 2131099690;
			
			// aapt resource value: 0x7f060045
			public const int hs__action_report_issue = 2131099717;
			
			// aapt resource value: 0x7f060044
			public const int hs__action_search = 2131099716;
			
			// aapt resource value: 0x7f060002
			public const int hs__actionbar_compat = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int hs__actionbar_compat_home = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int hs__actionbar_compat_item_refresh_progress = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hs__actionbar_compat_title = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int hs__actionbar_compat_up = 2131099651;
			
			// aapt resource value: 0x7f060042
			public const int hs__attach_screenshot = 2131099714;
			
			// aapt resource value: 0x7f060016
			public const int hs__confirmation = 2131099670;
			
			// aapt resource value: 0x7f060028
			public const int hs__contactUsContainer = 2131099688;
			
			// aapt resource value: 0x7f06002d
			public const int hs__contact_us_btn = 2131099693;
			
			// aapt resource value: 0x7f060020
			public const int hs__conversationDetail = 2131099680;
			
			// aapt resource value: 0x7f060005
			public const int hs__conversation_icon = 2131099653;
			
			// aapt resource value: 0x7f06002f
			public const int hs__customViewContainer = 2131099695;
			
			// aapt resource value: 0x7f060023
			public const int hs__email = 2131099683;
			
			// aapt resource value: 0x7f060013
			public const int hs__faqs_fragment = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int hs__fragment_holder = 2131099656;
			
			// aapt resource value: 0x7f06003e
			public const int hs__fullscreen_custom_content = 2131099710;
			
			// aapt resource value: 0x7f06002e
			public const int hs__helpful_text = 2131099694;
			
			// aapt resource value: 0x7f060014
			public const int hs__helpshiftActivityFooter = 2131099668;
			
			// aapt resource value: 0x7f06001c
			public const int hs__messageText = 2131099676;
			
			// aapt resource value: 0x7f060015
			public const int hs__messagesList = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int hs__newConversationFooter = 2131099657;
			
			// aapt resource value: 0x7f060017
			public const int hs__new_conversation = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int hs__new_conversation_btn = 2131099674;
			
			// aapt resource value: 0x7f060006
			public const int hs__notifcation_badge = 2131099654;
			
			// aapt resource value: 0x7f060031
			public const int hs__pager_tab_strip = 2131099697;
			
			// aapt resource value: 0x7f06002b
			public const int hs__question = 2131099691;
			
			// aapt resource value: 0x7f060026
			public const int hs__questionContent = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int hs__question_container = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int hs__question_fragment = 2131099685;
			
			// aapt resource value: 0x7f060007
			public const int hs__root = 2131099655;
			
			// aapt resource value: 0x7f060021
			public const int hs__screenshot = 2131099681;
			
			// aapt resource value: 0x7f06003c
			public const int hs__search_button = 2131099708;
			
			// aapt resource value: 0x7f06003a
			public const int hs__search_query = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int hs__search_query_clear = 2131099707;
			
			// aapt resource value: 0x7f060038
			public const int hs__sectionContainer = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int hs__sectionFooter = 2131099705;
			
			// aapt resource value: 0x7f060030
			public const int hs__sections_pager = 2131099696;
			
			// aapt resource value: 0x7f06001d
			public const int hs__sendMessageBtn = 2131099677;
			
			// aapt resource value: 0x7f06002c
			public const int hs__unhelpful_text = 2131099692;
			
			// aapt resource value: 0x7f060022
			public const int hs__username = 2131099682;
			
			// aapt resource value: 0x7f060027
			public const int hs__webViewParent = 2131099687;
			
			// aapt resource value: 0x7f06003f
			public const int hs__webview_main_content = 2131099711;
			
			// aapt resource value: 0x7f06000b
			public const int like_status = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int option_text = 2131099666;
			
			// aapt resource value: 0x7f06003d
			public const int progress_indicator = 2131099709;
			
			// aapt resource value: 0x7f06000a
			public const int ratingBar = 2131099658;
			
			// aapt resource value: 0x7f06001b
			public const int relativeLayout1 = 2131099675;
			
			// aapt resource value: 0x7f060037
			public const int report_issue = 2131099703;
			
			// aapt resource value: 0x7f060032
			public const int screenshotPreview = 2131099698;
			
			// aapt resource value: 0x7f060036
			public const int send = 2131099702;
			
			// aapt resource value: 0x7f06000e
			public const int submit = 2131099662;
			
			// aapt resource value: 0x7f060018
			public const int textView1 = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int hs__chat_max_lines = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int hs__conversation_detail_lines = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int hs__actionbar_compat = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int hs__actionbar_compat_home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hs__badge_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hs__conversation = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hs__csat_dialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hs__csat_holder = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int hs__csat_view = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int hs__faqs = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int hs__local_msg_request_screenshot = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int hs__messages_fragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int hs__messages_list_footer = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int hs__msg_confirmation_box = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int hs__msg_confirmation_status = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int hs__msg_request_screenshot = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int hs__msg_review_accepted = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int hs__msg_review_request = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int hs__msg_screenshot_status = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int hs__msg_txt_admin = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int hs__msg_txt_user = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int hs__new_conversation_fragment = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int hs__no_faqs = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int hs__question = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int hs__question_fragment = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int hs__questions_list = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int hs__screenshot_preview = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int hs__search_list_footer = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int hs__section = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int hs__simple_list_item_1 = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int hs__simple_list_item_2 = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int hs__simple_search_view = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int hs__video_loading_progress = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int hs__webview_custom_content = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Main = 2130903072;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int hs__add_conversation_menu = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int hs__faqs_fragment = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int hs__messages_menu = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int hs__show_conversation = 2131427331;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f080000
			public const int hs__notification_content_title = 2131230720;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090053
			public const int app_name = 2131296339;
			
			// aapt resource value: 0x7f090052
			public const int hello = 2131296338;
			
			// aapt resource value: 0x7f090000
			public const int hs__attach_btn = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int hs__attach_screenshot_btn = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int hs__ca_msg = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int hs__change_btn = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int hs__chat_hint = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int hs__confirmation_footer_msg = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int hs__confirmation_msg = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int hs__contact_us_btn = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int hs__conversation_detail_error = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int hs__conversation_end_msg = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int hs__conversation_header = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int hs__conversation_started_message = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int hs__cr_msg = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int hs__csat_additonal_feedback_message = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int hs__csat_dislike_message = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int hs__csat_like_message = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int hs__csat_message = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int hs__csat_option_message = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int hs__csat_submit_toast = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int hs__data_not_found_msg = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int hs__default_notification_content_title = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int hs__dm_video_loading = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int hs__done_btn = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int hs__email_hint = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int hs__email_required_hint = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int hs__empty_section = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int hs__faq_header = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int hs__faq_helpful_msg = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int hs__faq_unhelpful_msg = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int hs__faqs_search_footer = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int hs__faqs_updating = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int hs__faqs_updation_failure = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int hs__faqs_uptodate = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int hs__feedback_button = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int hs__help_header = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int hs__invalid_description_error = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int hs__invalid_email_error = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int hs__mark_helpful_toast = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int hs__mark_no = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int hs__mark_unhelpful_toast = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int hs__mark_yes = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int hs__mark_yes_no_question = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int hs__network_error_msg = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int hs__network_unavailable_msg = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int hs__new_conversation_btn = 2131296300;
			
			// aapt resource value: 0x7f09002d
			public const int hs__new_conversation_header = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int hs__new_conversation_hint = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int hs__new_conversation_msg = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int hs__notification_content_text = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int hs__privacy_policy = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int hs__question_header = 2131296306;
			
			// aapt resource value: 0x7f090033
			public const int hs__question_helpful_message = 2131296307;
			
			// aapt resource value: 0x7f090034
			public const int hs__question_unhelpful_message = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int hs__rate_button = 2131296309;
			
			// aapt resource value: 0x7f090036
			public const int hs__review_accepted_message = 2131296310;
			
			// aapt resource value: 0x7f090037
			public const int hs__review_btn = 2131296311;
			
			// aapt resource value: 0x7f090038
			public const int hs__review_close_button = 2131296312;
			
			// aapt resource value: 0x7f090039
			public const int hs__review_dialog_msg = 2131296313;
			
			// aapt resource value: 0x7f09003a
			public const int hs__review_dialog_negative_btn = 2131296314;
			
			// aapt resource value: 0x7f09003b
			public const int hs__review_dialog_neutral_btn = 2131296315;
			
			// aapt resource value: 0x7f09003c
			public const int hs__review_dialog_positive_btn = 2131296316;
			
			// aapt resource value: 0x7f09003d
			public const int hs__review_message = 2131296317;
			
			// aapt resource value: 0x7f09003e
			public const int hs__review_request_message = 2131296318;
			
			// aapt resource value: 0x7f09003f
			public const int hs__review_title = 2131296319;
			
			// aapt resource value: 0x7f090040
			public const int hs__rsc_progress_msg = 2131296320;
			
			// aapt resource value: 0x7f090041
			public const int hs__screenshot_add = 2131296321;
			
			// aapt resource value: 0x7f090042
			public const int hs__screenshot_cloud_attach_error = 2131296322;
			
			// aapt resource value: 0x7f090043
			public const int hs__screenshot_limit_error = 2131296323;
			
			// aapt resource value: 0x7f090044
			public const int hs__screenshot_remove = 2131296324;
			
			// aapt resource value: 0x7f090045
			public const int hs__screenshot_sent_msg = 2131296325;
			
			// aapt resource value: 0x7f090046
			public const int hs__screenshot_upload_error_msg = 2131296326;
			
			// aapt resource value: 0x7f090047
			public const int hs__search_footer = 2131296327;
			
			// aapt resource value: 0x7f090048
			public const int hs__search_hint = 2131296328;
			
			// aapt resource value: 0x7f090049
			public const int hs__search_title = 2131296329;
			
			// aapt resource value: 0x7f09004a
			public const int hs__send_msg_btn = 2131296330;
			
			// aapt resource value: 0x7f09004b
			public const int hs__sending_fail_msg = 2131296331;
			
			// aapt resource value: 0x7f09004c
			public const int hs__sending_msg = 2131296332;
			
			// aapt resource value: 0x7f09004d
			public const int hs__solved_btn = 2131296333;
			
			// aapt resource value: 0x7f09004e
			public const int hs__submit_conversation_btn = 2131296334;
			
			// aapt resource value: 0x7f09004f
			public const int hs__unsolved_btn = 2131296335;
			
			// aapt resource value: 0x7f090050
			public const int hs__username_blank_error = 2131296336;
			
			// aapt resource value: 0x7f090051
			public const int hs__username_hint = 2131296337;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int HSActionBarCompat = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int HSActionBarCompatItemBase = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int HSActionBarCompatProgressIndicator = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int HSActionBarCompatTitle = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int HSActionBarCompatTitleBase = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int HSActionBarThemedContext = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int HSDivider = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int HSEditTextAppTheme = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int Theme_Helpshift = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int Theme_Helpshift_Base = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int Theme_Helpshift_Light_DarkActionBar = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int Theme_Helpshift_Translucent = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int Widget_Helpshift_Base_ActionBar_TabText = 2131361804;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Theme_Helpshift = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 2
			public const int Theme_Helpshift_hs__actionBarTabTextStyle = 2;
			
			// aapt resource value: 1
			public const int Theme_Helpshift_hs__actionbarCompatItemBaseStyle = 1;
			
			// aapt resource value: 4
			public const int Theme_Helpshift_hs__actionbarCompatProgressIndicatorStyle = 4;
			
			// aapt resource value: 0
			public const int Theme_Helpshift_hs__actionbarCompatTitleStyle = 0;
			
			// aapt resource value: 3
			public const int Theme_Helpshift_hs__selectableItemBackground = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
